# Use node:18-alpine as the base image
FROM node:22-alpine

# Only install bash if you really need it
# RUN apk add --no-cache bash
# ENV SHELL=/bin/bash

# Install pnpm globally but clean npm cache afterward
RUN npm install -g pnpm && npm cache clean --force

# Set working directory
WORKDIR /app

# Copy only necessary files first
COPY package.json ./

# Install dependencies with pnpm and clean cache
RUN pnpm install \
    && pnpm store prune \
    && rm -rf /root/.cache /root/.local /root/.npm /root/.pnpm-store

# Copy remaining files
COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
