import { interceptor } from "@/lib/utils/logger";
import { Metadata } from "next";
import "./globals.css";
import { SharedSessionProvider } from "@/lib/auth/use-shared-session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Initialize console interception
if (process.env.NODE_ENV === "production") {
  interceptor.interceptConsole();
  interceptor.interceptGlobalErrors();
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SharedSessionProvider>{children}</SharedSessionProvider>
      </body>
    </html>
  );
}
